<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
* The feature(s) from the dataset that will be initially passed into the neural network model.
### Hidden Layer:
* Cannot be accessed and interacted. The NN does the calculations for us.
### Output Layer:
* Triggered by the activation function to transform the inputs to the desired outcome.
### Neuron:
* Or node. Receives inputs, multiplies each input by its wegiht, sum all of products and passes the ouputs to the next layer
### Weight:
* Initial weights are initially calculated by random then continually adjusted by the loss function with each iteration/epoch 
### Activation Function:
* Decides whether the cell will activate or not. Depending on which activation function is used, then the NN decides how much signal is passed onto the next layer
### Node Map:
* The architecture of the neural network or the layout of the node's path.
### Perceptron:
* A single node of a NN - One input and one ouput

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import numpy as np

np.random.seed(42)

# Create a 4 x 2 matrix of inputs - 4 rows and 2 cols
inputs = np.array([
    [0,0,1],
    [1,0,1],
    [0,1,1],
    [1,1,1]
])

# Target outputs - 4 rows and 1 col or 4 x 1 vector
target = np.array([[1], [1], [1], [0]])

In [2]:
# Activation function for outputs
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Back propagation - Updating weights
def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [3]:
# Random initial weights
# We are assuming the interaction of features is positive when only using np.random.random() since its range is 0 to 1.
# Starts off from 0 to 1. Double it then from 0 - 2. Subtract by 1 then from -1 to 1.
weights = 2 * np.random.random((3,1)) - 1
weights

array([[-0.25091976],
       [ 0.90142861],
       [ 0.46398788]])

In [4]:
# Calculate weighted sum of inputs 4x2 dot 2x1
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[0.46398788],
       [0.21306812],
       [1.3654165 ],
       [1.11449673]])

In [5]:
# Put into an activation function - sigmoid
# Above .50 is active and below .5 is inactive
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.61395979],
       [0.55306642],
       [0.79663861],
       [0.75296649]])

In [6]:
# Calculate error by taking the difference of the target and output
error = target - activated_output
error

array([[ 0.38604021],
       [ 0.44693358],
       [ 0.20336139],
       [-0.75296649]])

In [7]:
# Adjustment - Use loss Function(gradient descent) and back propagation
adjustment = error * sigmoid_derivative(activated_output)
adjustment

array([[ 0.08795756],
       [ 0.10360651],
       [ 0.04355646],
       [-0.16389299]])

In [8]:
# Update weights by adjusting the inputs and repeat calcuations- 2x4 dot 4x1 
weights += np.dot(inputs.T, adjustment)
weights

array([[-0.31120624],
       [ 0.78109208],
       [ 0.53521543]])

In [9]:
# Put it together to iterate more times

for i in range(10000):
    # 1. Calculate weighted sum of inputs and weight
    weighted_sum = np.dot(inputs, weights)
    
    # 2. Sigmoid Activation Function
    activated_output = sigmoid(weighted_sum)
    
    # 3. Calcuate the error - target - a_output
    error = target - activated_output
    
    # 4. Adjustment - Back Propagation
    adjustment = error * sigmoid_derivative(activated_output)
    
    # 5. Update weights by adjusting the inputs
    weights += np.dot(inputs.T, adjustment)

print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)
# Adding a third column to inputs variable and changing the weights from 2 to 3 will get more accurate outpute
## Not sure why this is happening. Maybe 2 features is not enough?

Weights after training
[[-11.83951525]
 [-11.83951525]
 [ 17.80813756]]
Output after training
[[0.99999998]
 [0.99744851]
 [0.99744851]
 [0.0028127 ]]


## Implement your own Perceptron Class and use it to classify a binary dataset like: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 
- [Titanic](https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv)
- [A two-class version of the Iris dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv)

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
print(df.shape)
df.head()

(768, 9)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [11]:
X = df.iloc[:, 0:10]
X = X.drop(columns='Outcome')
X = X.values

In [12]:
# Remeber to reshape or get an error when running the for loop below
y = df.iloc[:,8].values
y = y.reshape(-1,1)
y.shape

(768, 1)

In [13]:
X.shape

(768, 8)

In [14]:
X.T.shape

(8, 768)

In [15]:
# Use the correct weight vector by checking the number of features
weights = 2 * np.random.random((8,1)) - 1
weights.shape

(8, 1)

In [16]:
for i in range(100000):
    # 1. Calculate weighted sum of inputs and weight # 768x8 dot 8x1 = 768x1
    weighted_sum = np.dot(X, weights)
    
    # 2. Sigmoid Activation Function # 768x1
    activated_output = sigmoid(weighted_sum)
    
    # 3. Calcuate the error - target - a_output # 768x1
    error = y - activated_output

    # 4. Adjustment - Back Propagation # 768x1
    adjustment = error * sigmoid_derivative(activated_output)

    # 5. Update weights by adjusting the inputs # 8x768 dot768x1 = 8x1
    weights += np.dot(X.T, adjustment)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[141275.53434955]
 [  6742.00645115]
 [-23027.86779572]
 [ -1401.65998424]
 [   481.41729121]
 [-10803.56134499]
 [100817.37384167]
 [-15578.91664304]]
Output after training
[[1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.

In [17]:
# Check accuracy after training
# accuracy = correct / total
correct = 0
for i in range(len(X)):
    if y[i] == activated_output[i]:
        correct += 1
print(correct / len(X))

0.4700520833333333


## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?