# Backpropagation Practice

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [1]:
import numpy as np

np.random.seed(42)

# Three features - x1, x2, x3
X = np.array ([
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [0,1,0],
    [1,0,0],
    [1,1,1],
    [0,0,0]
])

# Target - y
y = np.array([
    [0],
    [1],
    [1],
    [1],
    [1],
    [0],
    [0]
])

In [2]:
class NeuralNetwork():
    def __init__(self):
        # Set-up Inputs, Hidden, & Output
        self.input = 3
        self.hidden = 4
        self.output = 1
        
        # Initial weights
        # 3x4 matrix for the first layer to hidden layer
        self.weights1 = np.random.randn(self.input, self.hidden)
        # 4x1 matrix for the hidden layer to output layer
        self.weights2 = np.random.randn(self.hidden, self.output)
        
    def sigmoid(self, s):
        '''
        Activation function
        '''
        return 1 / (1+np.exp(-s))
    
    def sigmoid_prime(self, s):
        '''
        Backpropagation function
        '''
        return s * (1-s)
    
    def feed_forward(self, X):
        '''
        Calculate the NN inference using feed forward.
        '''
    
        # Weighted sum of input and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weighted sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final Activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        '''
        Backward propagate through the network
        '''
        # Error in output
        self.o_error = y - o
        # Apply derivative of sigmoid to error
        self.o_delta = self.o_error * self.sigmoid_prime(o)
        
        # z2 error: how much the hidden layer weights were off
        self.z2_error = self.o_delta.dot(self.weights2.T)
        self.z2_delta = self.z2_error * self.sigmoid_prime(self.activated_hidden)
        
        # Adjust first set: input to hidden weights
        self.weights1 += X.T.dot(self.z2_delta)
        # Adjust second set: hidden to output weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [3]:
# Instantiate
nn = NeuralNetwork()

In [4]:
# Print statement 
for i in range(1000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 50 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.11922027]
 [0.06627476]
 [0.0844152 ]
 [0.07226438]
 [0.08832943]
 [0.05285008]
 [0.12139757]]
Loss: 
 0.49053127728032925
+---------EPOCH 2---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.1536457 ]
 [0.0965729 ]
 [0.12605453]
 [0.10385745]
 [0.13009871]
 [0.08589508]
 [0.15590308]]
Loss: 
 0.45643595198850395
+---------EPOCH 3---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.20756939]
 [0.15094684]
 [0.20046995]
 [0.16113519]
 [0.20567164]
 [0.15250002]
 [0.2119309 ]]
Loss: 
 0.4008639014783026
+---------EPOCH 4---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?